name: Deekery
favicon: null
layout_spectrum: 0.40899
typography_spectrum: 0.7849562007468194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5798807223327458
  lightness: 0.44803228438831866
  saturation: 0.1145583491306752
  rhythmicContrast: 0.4188293719198555
purpose: []
